### PR TITLE
Adds credits

### PR DESCRIPTION
**Pull request by dkastl**
Signed-off-by: Daniel Kastl <daniel@georepublic.de>

Changes proposed in this pull request:
- Give credits to the funding organizations

@gtt-project/maintainer

### CODE REVIEW

**Comment by dkastl** [comment]
@sanak , I just found this very old pull request. I think it's a good idea to add the credits still.

**Review by sanak — APPROVED** [review]
@dkastl Oh, yes.
Pointing `next` branch may be good, but I'll leave it to you.
Thanks!

**Comment by dkastl** [comment]
Oh, yes. I missed it points to `main` branch. That's actually from the time the PR was created already.

**Comment by dkastl** [comment]
Well, will merge directly to `main` to not to have to make yet another PR.

**Pull request merged**
